
-- DROP TABLE 
DROP TABLE PLAYLIST_SONG CASCADE CONSTRAINTS;
DROP TABLE PLAYLIST CASCADE CONSTRAINTS;
DROP TABLE SONG CASCADE CONSTRAINTS;
DROP TABLE ALBUM CASCADE CONSTRAINTS;

-- DROP 시퀀스
DROP SEQUENCE SEQ_ALBUM_ID;
DROP SEQUENCE SEQ_SONG_ID;
DROP SEQUENCE SEQ_PLAYLIST_ID;

--  TABLE 생성
CREATE TABLE ALBUM (
  ALBUM_ID NUMBER PRIMARY KEY,
  TITLE VARCHAR2(100),
  ARTIST VARCHAR2(100),
  RELEASE_DATE DATE,
  GENRE VARCHAR2(50),
  COVER_IMAGE_URL VARCHAR2(255)
);

CREATE TABLE SONG (
  SONG_ID NUMBER PRIMARY KEY,
  ALBUM_ID NUMBER REFERENCES ALBUM(ALBUM_ID),
  TITLE VARCHAR2(100),
  LENGTH VARCHAR2(10),
  TRACK_NO NUMBER
);

CREATE TABLE PLAYLIST (
  PLAYLIST_ID NUMBER PRIMARY KEY,
  NAME VARCHAR2(100),
  CREATED_AT DATE DEFAULT SYSDATE
);

CREATE TABLE PLAYLIST_SONG (
  PLAYLIST_ID NUMBER REFERENCES PLAYLIST(PLAYLIST_ID),
  SONG_ID NUMBER REFERENCES SONG(SONG_ID),
  PRIMARY KEY (PLAYLIST_ID, SONG_ID)
);

-- 시퀀스 생성

CREATE SEQUENCE SEQ_ALBUM_ID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_SONG_ID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_PLAYLIST_ID START WITH 1 INCREMENT BY 1;

-- 더미 데이터: 앨범

INSERT INTO ALBUM (
  ALBUM_ID, TITLE, ARTIST, RELEASE_DATE, GENRE, COVER_IMAGE_URL
) VALUES (
  SEQ_ALBUM_ID.NEXTVAL, 'Divide', 'Ed Sheeran', TO_DATE('2017-03-03', 'YYYY-MM-DD'), 'Pop', 'https://images.genius.com/fb4b28da4a8f736b6f51df908257e0fd.1000x563x1.jpg'
);

INSERT INTO ALBUM (
  ALBUM_ID, TITLE, ARTIST, RELEASE_DATE, GENRE, COVER_IMAGE_URL
) VALUES (
  SEQ_ALBUM_ID.NEXTVAL, 'Map of the Soul: 7', 'BTS', TO_DATE('2020-02-21', 'YYYY-MM-DD'), 'K-Pop', 'https://image.bugsm.co.kr/album/images/500/203012/20301226.jpg'
);

-- 더미 데이터: 곡

INSERT INTO SONG (
  SONG_ID, ALBUM_ID, TITLE, LENGTH, TRACK_NO
) VALUES (
  SEQ_SONG_ID.NEXTVAL, 1, 'Shape of You', '03:53', 1
);

INSERT INTO SONG (
  SONG_ID, ALBUM_ID, TITLE, LENGTH, TRACK_NO
) VALUES (
  SEQ_SONG_ID.NEXTVAL, 1, 'Perfect', '04:23', 2
);

INSERT INTO SONG (
  SONG_ID, ALBUM_ID, TITLE, LENGTH, TRACK_NO
) VALUES (
  SEQ_SONG_ID.NEXTVAL, 2, 'ON', '04:06', 1
);

INSERT INTO SONG (
  SONG_ID, ALBUM_ID, TITLE, LENGTH, TRACK_NO
) VALUES (
  SEQ_SONG_ID.NEXTVAL, 2, 'Black Swan', '03:18', 2
);

-- 더미 데이터: 플레이리스트

INSERT INTO PLAYLIST (
  PLAYLIST_ID, NAME
) VALUES (
  SEQ_PLAYLIST_ID.NEXTVAL, 'My Favorites'
);

-- 더미 데이터: 플레이리스트에 곡 추가

INSERT INTO PLAYLIST_SONG (
  PLAYLIST_ID, SONG_ID
) VALUES (
  1, 1
);

INSERT INTO PLAYLIST_SONG (
  PLAYLIST_ID, SONG_ID
) VALUES (
  1, 3
);

commit;
